# Generated by Django 4.2.27 on 2026-01-19 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('country', models.CharField(blank=True, default='', max_length=80)),
                ('admin1', models.CharField(blank=True, default='', max_length=120)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('timezone', models.CharField(default='auto', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'lat', 'lon')},
            },
        ),
    ]
